version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Test
          command: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              only: master
