version: 2
jobs:
  test:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              only: master
